### ISSUE TITLE
Error in nu || nv : invalid 'x' type in 'x || y'

### ISSUE THREAD

**Issue by JiaFu1992** [bcm-uga/LEA3_simulation_script#1]
Hello,

I am computing genetic offset using the method you provided in "LEA3_athaliana_offset_computation.R" -- namely the function genetic.offset() in the R package LEA3, and got the error as the title. I have tried my own data, the data attached to your paper (Gain & François, 2020), and the example in the manual of genetic.offset() of LEA, and all them sent me this error, which happened on CentOS. I then tried the example data on Ubuntu, and got the same error returned. I also installed a few different LEA versions, which made no sense. I traced back this error with traceback() and got the following informations:

`> traceback()
4: La.svd(x, nu, nv)
3: svd(D %*% t(Q) %*% scale(Y, scale = FALSE), nu = K)
2: lfmm2(input = Y, env = X, K = K)
1: genetic.offset(mod2, input = Xsc, env = bio, new.env = bio_fut_26, 
       pop.labels = coord$Cluster)
`

When I used Windows R, I can deal with the example data, so **it seems to happen only on Linux**. For my own data is too large to be handled on PCs, I still have to solve this problem. Do you have any idea on how could this happen, and how to solve this problem?

Best regards,

Jia-fu

**Comment by francoio** [comment]
hello, 

The LEA::genetic.offset() function has changed this example was released. I suggest that you remove.packages("LEA")  and re-install the package from GitHub 

devtools::install_github("bcm-uga/LEA")

this is equivalent to the bioconductor devel version which is regularly checked for linux windows and macosx

Note that the error message is difficult to understand. This seems to be an error in the svd not in our own code. Could you check the version of LEA used?

send me a dirct email if the function doesn't work after reinstalling.

olivier
